### ISSUE TITLE
Doesn't work with .tmp files

### ISSUE THREAD

**Issue by ikoruk** [Delgan/qml-format#1]
The extension does not work at all for me. I get the following error:

```
Formatting of 'test.qml' failed (1):
'Command failed: /usr/bin/qmlformat [...]/test.qml.formatting-q2vjwvvm.tmp
[Dom][Universe] Error: Could not detect type of file [...]/test.qml.formatting-q2vjwvvm.tmp
[Dom] Error: Unexpected file to load: '[...]/test.qml.formatting-q2vjwvvm.tmp'
Failed to parse [...]/test.qml.formatting-q2vjwvvm.tmp '.
```

**Comment by Delgan** [comment]
Hi @ikoruk.

Can you please share the content of `test.qml`, the `qmlformat` version and the OS you're using?

**Comment by Delgan** [comment]
So, I only tested it with Qt5 and didn't realize that latest versions of `qmlformat` also checks the file extension before formatting.

Thanks for the bug report. Please, upgrade to `v1.0.2`, it should be fixed by now. :+1:
