### ISSUE TITLE
Formatting doesn't work

### ISSUE THREAD

**Issue by klaus-zaeper-horsch** [Delgan/qml-format#3]
Every time I try to format a QML-FIle, it shows:
Formatting of 'main.qml' failed (ENOENT): 'spawn qmlformat ENOENT'.

**Comment by Delgan** [comment]
Hi.

By default, the extension tries to call `qmlformat` command. If it's not available in your `PATH` by default, you can specify the path toward the `qmlformat` in the settings:

```
{
    "qmlFormat.command": "/usr/lib/qt6/bin/qmlformat",
}
```

See requirements and example [in the README](https://github.com/Delgan/qml-format#requirements).

**Comment by klaus-zaeper-horsch** [comment]
Thanks a lot!

**Comment by Delgan** [comment]
I'm closing the ticket as it seems resolved. :+1:
