### ISSUE TITLE
Enable the use of environment variables in the path to `qmlformat`

### ISSUE THREAD

**Issue by emmenlau** [Delgan/qml-format#6]
We have our build environments in different software trees. The selection is performed based on environment variables. Basically something like `SOFTWARE_TREE_ROOT=/path/to/tree`. I would like to set the path to `qmlformat` with a reference to such environment variable.

Is that possible, or could it be added? VSCode seems to have a dedicated syntax for this: https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

**Comment by Delgan** [comment]
Hi.

Unfortunately, it seems VS Code does not support variable substitution in settings file: https://github.com/microsoft/vscode/issues/2809

I don't really think this feature should be handled by the extension itself.

Can you by any chance arrange the `PATH` environment variable so so that it finds the `qmlformat` executable adequately?

**Comment by emmenlau** [comment]
Hi!
I can say that there are extensions that can work with variables. For example, cmake tools can use:
```
    "cmake.cmakePath": "${MY_SOFT_DEST}/Tools/bin/cmake",
```
I'm not sure how the substitution is implemented, if VSCode takes care of it, or the extension itself?

**Comment by Delgan** [comment]
> I'm not sure how the substitution is implemented, if VSCode takes care of it, or the extension itself?

This is an implementation specific to their extension, with all that this entails in terms of added complexity and maintenance to the code.

How do you switch from one environment to another in your use case? Don't you have the option of updating `PATH` at the same time or updating a symlink to the appropriate `qmlformat` executable?
